In [4]:
print("Hello world")

Hello world


In [5]:
import numpy as np

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import tensorflow as tf

In [62]:
matrix = tf.constant([[1, 2, 0], [4, 5, 6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [4, 5, 6]], dtype=int32)>

In [63]:
seq = 1 - tf.cast(tf.math.equal(matrix, 0), tf.float32)

In [64]:
seq

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 0.],
       [1., 1., 1.]], dtype=float32)>

In [65]:
seq[:, tf.newaxis, :] 

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[1., 1., 0.]],

       [[1., 1., 1.]]], dtype=float32)>

In [22]:
vector = tf.constant([1, 2, 3])  # Shape: (3,)
print(vector)
expanded = vector[tf.newaxis, :]
print(expanded)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [8]:
tf.linalg.band_part(tf.ones((1, 10, 10)), -1, 0)

<tf.Tensor: shape=(1, 10, 10), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32)>

In [9]:
import textwrap

In [10]:
wrapper = textwrap.TextWrapper(width=70)

In [38]:
import pandas as pd

# Crear documentos como Series
document = pd.Series([
    "[SOS] amanda: i baked cookies. do you want some? jerry: sure! amanda: i'll bring you tomorrow :-) [EOS]",
    "[SOS] sarah: did you finish the project? mike: almost done, just need to review the last section. sarah: great! send it when ready. mike: will do by 5pm. [EOS]",
    "[SOS] lisa: the meeting is cancelled. tom: really? why? lisa: the client rescheduled for next week. tom: okay, thanks for letting me know. [EOS]",
    "[SOS] emily: can you pick up groceries? david: sure, what do we need? emily: milk, bread, and eggs. david: got it, i'll go after work. [EOS]",
    "[SOS] alex: the concert tickets are sold out. jordan: that's disappointing. alex: yeah, but there's another show next month. jordan: let's get those then! [EOS]"
])
document

0    [SOS] amanda: i baked cookies. do you want som...
1    [SOS] sarah: did you finish the project? mike:...
2    [SOS] lisa: the meeting is cancelled. tom: rea...
3    [SOS] emily: can you pick up groceries? david:...
4    [SOS] alex: the concert tickets are sold out. ...
dtype: object

In [39]:
# Crear resúmenes como Series
summary = pd.Series([
    "[SOS] amanda baked cookies and will bring jerry some tomorrow. [EOS]",
    "[SOS] mike is finishing the project and will send it to sarah by 5pm. [EOS]",
    "[SOS] the meeting was cancelled and rescheduled for next week. [EOS]",
    "[SOS] david will pick up milk, bread, and eggs after work. [EOS]",
    "[SOS] concert tickets are sold out, but alex and jordan plan to get tickets for next month's show. [EOS]"
])
summary

0    [SOS] amanda baked cookies and will bring jerr...
1    [SOS] mike is finishing the project and will s...
2    [SOS] the meeting was cancelled and reschedule...
3    [SOS] david will pick up milk, bread, and eggs...
4    [SOS] concert tickets are sold out, but alex a...
dtype: object

In [40]:
documents_and_summary = pd.concat([document, summary], ignore_index=True)
documents_and_summary

0    [SOS] amanda: i baked cookies. do you want som...
1    [SOS] sarah: did you finish the project? mike:...
2    [SOS] lisa: the meeting is cancelled. tom: rea...
3    [SOS] emily: can you pick up groceries? david:...
4    [SOS] alex: the concert tickets are sold out. ...
5    [SOS] amanda baked cookies and will bring jerr...
6    [SOS] mike is finishing the project and will s...
7    [SOS] the meeting was cancelled and reschedule...
8    [SOS] david will pick up milk, bread, and eggs...
9    [SOS] concert tickets are sold out, but alex a...
dtype: object

In [42]:
# Verificar
print(f"Documentos: {len(document)}")
print(f"Resúmenes: {len(summary)}")
print(f"Total: {len(documents_and_summary)}")
print("\nEjemplo - Documento original:")
print(document.iloc[0])
print("\nEjemplo - Resumen correspondiente:")
print(summary.iloc[0])

Documentos: 5
Resúmenes: 5
Total: 10

Ejemplo - Documento original:
[SOS] amanda: i baked cookies. do you want some? jerry: sure! amanda: i'll bring you tomorrow :-) [EOS]

Ejemplo - Resumen correspondiente:
[SOS] amanda baked cookies and will bring jerry some tomorrow. [EOS]


In [43]:
filters = '!"#$%&()*+,-./:;<=>?@\\^_`{|}~\t\n'
oov_token = '[UNK]'

tokenizer = tf.keras.preprocessing.text.Tokenizer(filters=filters, oov_token=oov_token, lower=False)

In [44]:
tokenizer.fit_on_texts(documents_and_summary)

In [45]:
document

0    [SOS] amanda: i baked cookies. do you want som...
1    [SOS] sarah: did you finish the project? mike:...
2    [SOS] lisa: the meeting is cancelled. tom: rea...
3    [SOS] emily: can you pick up groceries? david:...
4    [SOS] alex: the concert tickets are sold out. ...
dtype: object

In [46]:
inputs = tokenizer.texts_to_sequences(document)
targets = tokenizer.texts_to_sequences(summary)

In [49]:
vocab_size = len(tokenizer.word_index) + 1

In [50]:
print(f'Size of vocabulary: {vocab_size}')

Size of vocabulary: 95


In [51]:
print("\nPrimeras 20 palabras del vocabulario:")
for word, idx in list(tokenizer.word_index.items())[:20]:
    print(f"{word}: {idx}")


Primeras 20 palabras del vocabulario:
[UNK]: 1
[SOS]: 2
[EOS]: 3
the: 4
and: 5
you: 6
will: 7
for: 8
next: 9
amanda: 10
do: 11
sarah: 12
mike: 13
to: 14
it: 15
david: 16
alex: 17
tickets: 18
jordan: 19
baked: 20


In [52]:
# Ver cuántas palabras únicas hay en cada texto
print("\nPalabras únicas por documento:")
for i, doc in enumerate(document):
    words = doc.split()
    unique_words = set(words)
    print(f"Documento {i}: {len(unique_words)} palabras únicas")


Palabras únicas por documento:
Documento 0: 16 palabras únicas
Documento 1: 26 palabras únicas
Documento 2: 20 palabras únicas
Documento 3: 24 palabras únicas
Documento 4: 23 palabras únicas


In [53]:
# Limit the size of the input and output data for being able to run it in this environment.
encoder_maxlen = 150
decoder_maxlen = 50

In [54]:
inputs = tf.keras.preprocessing.sequence.pad_sequences(inputs, maxlen=encoder_maxlen, padding='post', truncating='post')
inputs

array([[ 2, 10, 55, 20, 21, 11,  6, 56, 22, 23, 24, 10, 25, 26,  6, 27,
         3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 2, 12, 57,  6, 58,  4, 28, 13, 59, 60, 61, 29, 14, 62,  4, 63,
        64, 12, 65, 30, 15, 66, 67, 13,  7, 11, 31, 32,  3,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,

In [55]:
targets = tf.keras.preprocessing.sequence.pad_sequences(targets, maxlen=decoder_maxlen, padding='post', truncating='post')
targets

array([[ 2, 10, 20, 21,  5,  7, 26, 23, 22, 27,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2, 13, 35, 91,  4, 28,  5,  7, 30, 15, 14, 12, 31, 32,  3,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2,  4, 34, 92, 36,  5, 38,  8,  9, 39,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2, 16,  7, 41, 42, 43, 44,  5, 45, 46, 47,  3,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2, 48, 18, 49, 50, 51, 52, 17,  5, 19, 93, 14, 54, 18,  8, 

In [56]:
inputs = tf.cast(inputs, dtype=tf.int32)
inputs

<tf.Tensor: shape=(5, 150), dtype=int32, numpy=
array([[ 2, 10, 55, 20, 21, 11,  6, 56, 22, 23, 24, 10, 25, 26,  6, 27,
         3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 2, 12, 57,  6, 58,  4, 28, 13, 59, 60, 61, 29, 14, 62,  4, 63,
        64, 12, 65, 30, 15, 66, 67, 13,  7, 11, 31, 32,  3,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [57]:
targets = tf.cast(targets, dtype=tf.int32)
targets

<tf.Tensor: shape=(5, 50), dtype=int32, numpy=
array([[ 2, 10, 20, 21,  5,  7, 26, 23, 22, 27,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2, 13, 35, 91,  4, 28,  5,  7, 30, 15, 14, 12, 31, 32,  3,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2,  4, 34, 92, 36,  5, 38,  8,  9, 39,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2, 16,  7, 41, 42, 43, 44,  5, 45, 46, 47,  3,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0],
       [ 2, 48, 18, 4

In [60]:
# Create the final training dataset.
BUFFER_SIZE = 10000
BATCH_SIZE = 64

dataset = tf.data.Dataset.from_tensor_slices((inputs, targets)).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
dataset.take(1).get_single_element()

(<tf.Tensor: shape=(5, 150), dtype=int32, numpy=
 array([[ 2, 12, 57,  6, 58,  4, 28, 13, 59, 60, 61, 29, 14, 62,  4, 63,
         64, 12, 65, 30, 15, 66, 67, 13,  7, 11, 31, 32,  3,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0],
        [ 2, 33,  4, 34, 35, 36, 37, 68, 69, 33,  4, 70, 38,  8,  9, 39,
         37, 71, 72,  8, 73, 74, 75,  3,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0, 

In [68]:
def positional_encoding(positions, d_model):
    """
    Precomputes a matrix with all the positional encodings 
    
    Arguments:
        positions (int): Maximum number of positions to be encoded 
        d_model (int): Encoding size 
    
    Returns:
        pos_encoding (tf.Tensor): A matrix of shape (1, position, d_model) with the positional encodings
    """
    
    position = np.arange(positions)[:, np.newaxis]
    k = np.arange(d_model)[np.newaxis, :]
    i = k // 2
    
    # initialize a matrix angle_rads of all the angles 
    angle_rates = 1 / np.power(10000, (2 * i) / np.float32(d_model))
    angle_rads = position * angle_rates
  
    # apply sin to even indices in the array; 2i
    angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
  
    # apply cos to odd indices in the array; 2i+1
    angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
    
    pos_encoding = angle_rads[np.newaxis, ...]
    
    return tf.cast(pos_encoding, dtype=tf.float32)

In [69]:
def create_padding_mask(decoder_token_ids):
    """
    Creates a matrix mask for the padding cells
    
    Arguments:
        decoder_token_ids (matrix like): matrix of size (n, m)
    
    Returns:
        mask (tf.Tensor): binary tensor of size (n, 1, m)
    """    
    seq = 1 - tf.cast(tf.math.equal(decoder_token_ids, 0), tf.float32)
  
    # add extra dimensions to add the padding to the attention logits. 
    # this will allow for broadcasting later when comparing sequences
    return seq[:, tf.newaxis, :] 


def create_look_ahead_mask(sequence_length):
    """
    Returns a lower triangular matrix filled with ones
    
    Arguments:
        sequence_length (int): matrix size
    
    Returns:
        mask (tf.Tensor): binary tensor of size (sequence_length, sequence_length)
    """
    mask = tf.linalg.band_part(tf.ones((1, sequence_length, sequence_length)), -1, 0)
    return mask 

In [ ]:
# GRADED FUNCTION: scaled_dot_product_attention
def scaled_dot_product_attention(q, k, v, mask):
    """
    Calculate the attention weights.
      q, k, v must have matching leading dimensions.
      k, v must have matching penultimate dimension, i.e.: seq_len_k = seq_len_v.
      The mask has different shapes depending on its type(padding or look ahead) 
      but it must be broadcastable for addition.

    Arguments:
        q (tf.Tensor): query of shape (..., seq_len_q, depth)
        k (tf.Tensor): key of shape (..., seq_len_k, depth)
        v (tf.Tensor): value of shape (..., seq_len_v, depth_v)
        mask (tf.Tensor): mask with shape broadcastable 
              to (..., seq_len_q, seq_len_k). Defaults to None.

    Returns:
        output -- attention_weights
    """
    ### START CODE HERE ###
    
    # Multiply q and k transposed.
    matmul_qk = tf.matmul(q, k.T)

    # scale matmul_qk with the square root of dk
    dk = tf.cast(tf.shape(k)[-1], tf.float32)
    scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)

    # add the mask to the scaled tensor.
    if mask is not None:  # Don't replace this None
        scaled_attention_logits += ((1 - mask) * -1e9)

    # softmax is normalized on the last axis (seq_len_k) so that the scores add up to 1.
    attention_weights = tf.nn.softmax(scaled_attention_logits, axis=-1)

    # Multiply the attention weights by v
    output = tf.matmul(attention_weights, v)
    
    ### END CODE HERE ###

    return output, attention_weights