In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import tensorflow as tf

In [18]:
matrix = tf.constant([[1, 2, 0], [4, 5, 6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [4, 5, 6]], dtype=int32)>

In [19]:
seq = 1 - tf.cast(tf.math.equal(matrix, 0), tf.float32)

In [20]:
seq[:, tf.newaxis, :] 

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[1., 1., 0.]],

       [[1., 1., 1.]]], dtype=float32)>

In [22]:
vector = tf.constant([1, 2, 3])  # Shape: (3,)
print(vector)
expanded = vector[tf.newaxis, :]
print(expanded)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [23]:
tf.linalg.band_part(tf.ones((1, 10, 10)), -1, 0)

<tf.Tensor: shape=(1, 10, 10), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32)>